# Generated by Django 5.1.6 on 2025-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_m', '0002_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
