# Generated by Django 5.1.6 on 2025-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_m', '0003_media_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
    ]
