# Generated by Django 5.1.6 on 2025-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_m', '0004_remove_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='desc',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.TextField(max_length=15),
        ),
    ]
