# Generated by Django 5.1.6 on 2025-03-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_m', '0005_media_desc_alter_media_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
        migrations.AddField(
            model_name='media',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
