# Generated by Django 5.1.6 on 2025-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_m', '0006_remove_media_video_media_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='media',
            name='files',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
